from os import system

system("pip3 install pyqt5")
system("pip3 install PyQtWebEngine")
system("pip3 install webbrowser")
system("pip3 install pyglet")
system("pip3 install pygame")
system("pip3 install anyio")
system("pip3 install idna")
system("pip3 install tkinter")
system("pip3 install Markdown")
system("pip3 install numpy")
system("pip3 install uniform")
system("pip3 install Tk")
system("pip3 install wx")